### ISSUE TITLE
Switch to /audios/mp3 from /mp3

### ISSUE THREAD

**Issue by not-nocturnal** [jamesnicolas/yomichan-forvo-server#11]
I've noticed frequent differences in volume between the audio the addon gives and the audio that the forvo website gives, with the addon's audio often being much louder or quieter, leading me to believe that /mp3 is the pre-normalization audio file. Switching to /audios/mp3 might result in a better experience.

**Comment by jamesnicolas** [comment]
@not-nocturnal Can you give an example of a word that is much louder or much quieter? Doing some investigation right now, and it seems like the `/audios/mp3` path doesn't actually exist anymore, but there is a new subdomain for their files which is at `audio12.forvo.com` as opposed to the existing `audio00.forvo.com` domain.

**Comment by not-nocturnal** [comment]
攻防 spoken by kayana is a good example, especially as the other voices for that word do not have such a noticeable volume difference between sources. It does seem to be possible to get audio from the old location (as this is what anki-forvo-dl uses), but the site itself does get them from audio12 now.

**Comment by jamesnicolas** [comment]
Oh yeah the /audios/mp3 URL does still work, I just have to get the right filename. Thanks for the clear working example, it helped a lot with the investigation! I pushed a few new fixes and features, including the /audios/mp3 one to the main branch, but want to test it out a bit more first to see if it works consistently before releasing. Feel free to try it out.

**Comment by jamesnicolas** [comment]
@not-nocturnal I deployed the changes, let me know if it works for you.

**Comment by not-nocturnal** [comment]
Tested them today, and it seems to be working!
