### ISSUE TITLE
Custom URL(JSON) option does not exist in Yomichan's Firefox version.

### ISSUE THREAD

**Issue by zirong679** [jamesnicolas/yomichan-forvo-server#14]
I am unable to get the add on to work in the Firefox version of Yomichan because the JSON option does not exist in the settings. Is there a way to work around this issue? 

<img width="1235" alt="Screenshot 2023-02-23 at 1 11 45 PM" src="https://user-images.githubusercontent.com/122044026/220826022-22d6eead-8c99-4ef4-b947-b1087946f04e.png">

**Comment by Dewi02** [comment]
The firefox addon hasn't been updated since June 5, 2020.
You would have to sideload a newer version from the [yomichan github](https://github.com/FooSoft/yomichan)

**Comment by zirong679** [comment]
Sorry for spaming your notifications. I moved back to using chrome because I tried using Firefox to reduce my browser's cpu consumption but it did not work. In the future if anyone wants to try using Firefox they can perhaps try the step above I guess.
