### ISSUE TITLE
Two Languages at a time

### ISSUE THREAD

**Issue by ghost** [jamesnicolas/yomichan-forvo-server#15]
is there a way to set two different languages at the same time?

**Comment by jamesnicolas** [comment]
@RyanOrigens it seems like the /search page only lets you search one language at a time, however, the /word page contains all language for a word, so you could include those languages without making an extra call. I don't have the capacity to make that change right now but a PR would be welcome.

**Comment by ghost** [comment]
Hey,

I would love to help with a pull request, but i'm not a developer though.

Thanks for the response

**Comment by jamesnicolas** [comment]
@RyanOrigens #17 submitted a PR that allows you to specify the language in the URL. let me know if this what you wanted
 
![vivaldi_ULkOQ9luhX](https://github.com/jamesnicolas/yomichan-forvo-server/assets/2841145/a18f8c50-e32a-4bf3-9926-dc65c9058da8)
![vivaldi_zEZgLt7qDV](https://github.com/jamesnicolas/yomichan-forvo-server/assets/2841145/7665f4d8-0e3e-4ba7-9887-62ee0066317e)

**Comment by ghost** [comment]
Yeah, it was exactly what i wanted, thank you.
