### ISSUE TITLE
Addon not working anymore

### ISSUE THREAD

**Issue by qwasrmachine** [jamesnicolas/yomichan-forvo-server#25]
That is it, the local server is running as usual but it can't fetch any audio from forvo

Yomitan unable to fetch audio from http://localhost:8770/?term={term}&reading={reading}&language=zh
(already tried without "&language=zh")
![image](https://github.com/jamesnicolas/yomichan-forvo-server/assets/104048544/a0496fad-ea95-4b17-b268-2502c79c188c)

And yes, anki is open while I do this, this addon was working perfectly for mandarin chinese some months ago, but now that I came back to language learning it stopped working all of a sudden

**Comment by shigeyukey** [comment]
This issue is due to Forvo changing their website, all add-ons for Forvo are no longer available (my Forvo-addon-fork no longer works too). So far the workaround is unknown.

**Comment by jamesnicolas** [comment]
@qwasrmachine Is it still broken? I just tested it and it seems to be working. Not sure if forvo reverted something?

**Comment by powerstomp** [comment]
I'm pretty sure it was a cloudflare verification issue, it seems to be back to normal now.

**Comment by qwasrmachine** [comment]
It's working again, looks like that happens sometimes..

**Comment by Bolphins** [comment]
I'm having a repeat of the same issue where the extension is not fetching audio, is anyone also having this problem?

**Comment by shigeyukey** [comment]
As puinyu says this seems to be the cloudflare verification issue, I develop fork of Forvo pronunciation downloader add-on, it works and sometimes doesn't work, currently it doesn't work.
