### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by JuneStepp** [jamesnicolas/yomichan-forvo-server#28]
Can you add a license to this project, so it's easier to package and contribute to?

Here's a GitHub article on licenses in case you aren't familiar: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by jamesnicolas** [comment]
added in 364fc6d5d10969f516e0fa283460dfaf08c98e15
