### ISSUE TITLE
A method to scrape all Forvo pronunciations 

### ISSUE THREAD

**Issue by ghost** [jamesnicolas/yomichan-forvo-server#5]
A method to scrape all Forvo pronunciations is now available:

https://ankiweb.net/shared/info/858591644#:~:text=a%20method%20to%20scrape%20all

You can choose your target Language. Works really well !

**Comment by jamesnicolas** [comment]
Why is this an issue?

**Comment by jamesnicolas** [comment]
Closing since there's nothing for me to do here
